version: '3.3'

networks:
  testnet:
    external: true

services:
  npm: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: 
    #set as unless-stopped, always, or never 
    #(don't do never unless you have a good reason)
    ports:
      - 80:80
      - 443:443
      - :81 
      #set a local port (above 2000 is recommended 
      #cuz below that gets used more often)
    volumes:
      - :/data
      - :/etc/letsencrypt
      #set a local directory. recommended to 
      #make a folder in the working directory of this file 
      #and a different folder for each service
      #i recommend naming these folder after the service
    networks:
      - testnet
    environment:
      - PUID=
      - PGID=
      #find the PUID and PGID by running the command id
      #the UID and GID are the PUID and PGID respectively
      - TZ=America/Los_Angeles